services:
  db:
    image: "mysql:8.0"
    container_name: db
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/logs:/var/log/mysql
    ports:
      - "${SPRING_DATABASE_PORT}:${SPRING_DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      MYSQL_USER: ${SPRING_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATABASE_NAME}
    env_file:
      - .env
    networks:
      - jobspoon-net

  redis:
    image: redis:7.0.4
    container_name: redis-container
    hostname: redis-container
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "${SPRING_DATA_REDIS_PORT}:${SPRING_DATA_REDIS_PORT}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - jobspoon-net

  server:
    image: ghcr.io/imcoder0000/spring-backend:latest
    container_name: spring-backend
    restart: unless-stopped
    volumes:
      - appdata:/app
    depends_on:
      - db
      - redis
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: >
      bash -c "/wait-for-it.sh db:${SPRING_DATABASE_PORT} -t 30 &&
               /wait-for-it.sh redis-container:${SPRING_DATA_REDIS_PORT} -t 30 &&
               java -jar /app.jar"
    env_file:
      - .env
    networks:
      - jobspoon-net

networks:
  jobspoon-net:
    external: true

volumes:
  dbdata:
    driver: local
  appdata:
    driver: local