version: "3.7"

services:
  db:
    image: "mysql:8.0"
    container_name: db
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/mysql/logs:/var/log/mysql
    ports:
      - "${SPRING_DATABASE_PORT}:${SPRING_DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      MYSQL_USER: ${SPRING_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATABASE_NAME}
    env_file:
      - .env
    networks:
      - jobspoon-net

  redis:
    image: redis:7.0.4
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    container_name: redis-container
    hostname: redis-container
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "${SPRING_DATA_REDIS_PORT}:${SPRING_DATA_REDIS_PORT}"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - jobspoon-net

  server:
    image: ghcr.io/${GITHUB_ACTOR}/spring-backend:latest
    build: .
    container_name: spring-backend
    volumes:
      - appdata:/app
    depends_on:
      - db
      - redis
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:3306 -t 15
        java -jar /app.jar
    env_file:
      - .env
    networks:
      - jobspoon-net

networks:
  jobspoon-net:
    driver: bridge

volumes:
  dbdata:
    driver: local
  appdata:
    driver: local
