version: "3.7"

services:
  server:
    image: ghcr.io/imcoder0000/spring-backend:latest
    build: .
    container_name: spring-backend
    volumes:
      - appdata:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - REDIS_HOST=redis-container
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh mysql-container:3306 -t 15
        java -jar /app.jar
    networks:
      - app

networks:
  app:
    external: true

volumes:
  appdata:
    driver: local
